name: Generate Vocabulary Data

on:
  workflow_dispatch:  # 手动触发
  push:
    paths:
      - 'dict/**'
      - 'scripts/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Parse dictionary files
        run: npm run parse

      - name: Generate vocabulary data with ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate

      - name: Commit and push generated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: generate vocabulary data" && git push)
